[features]
seeds = false
skip-lint = false
[programs.localnet]
bond = "FXUEM9ZfqeWkAtHDCoCGB7C9cwNW1JcyhXB47i9J6B37"
[programs.devnet]
bond = "FXUEM9ZfqeWkAtHDCoCGB7C9cwNW1JcyhXB47i9J6B37"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/m/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
