[features]
seeds = false
skip-lint = false
[programs.localnet]
bond = "ECte5vr5zJkRVnEPY9XPkgq3JFfFkthrMKxLk6gfa7v4"
[programs.devnet]
bond = "ECte5vr5zJkRVnEPY9XPkgq3JFfFkthrMKxLk6gfa7v4"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/m/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
